services:
  lueftung-serverraum:
    build: .
    image: lueftung-serverraum:latest
    container_name: lueftung-serverraum
    restart: unless-stopped
    privileged: true
    volumes:
      - ./messwerte.csv:/app/messwerte.csv
