services:
  lueftung-serverraum:
    build: .
    image: lueftung-serverraum:latest
    container_name: lueftung-serverraum
    restart: unless-stopped
    privileged: true
    ports:
      - "8000:8000"
    environment:
      SENSOR_MODUS: real      # "real" für echten BME280-Sensor
      LUEFTER_MODUS: real     # "real" für echtes GPIO-Relais
    volumes:
      - ./messwerte.csv:/app/messwerte.csv
